In [121]:
import pandas as pd

# Read the file into a dataframe
df = pd.read_csv('/content/BBC News Train.csv')

df.index=range(0,len(df))

In [122]:
df.loc[:,'Text']

0       worldcom ex-boss launches defence lawyers defe...
1       german business confidence slides german busin...
2       bbc poll indicates economic gloom citizens in ...
3       lifestyle  governs mobile choice  faster  bett...
4       enron bosses in $168m payout eighteen former e...
                              ...                        
1485    double eviction from big brother model caprice...
1486    dj double act revamp chart show dj duo jk and ...
1487    weak dollar hits reuters revenues at media gro...
1488    apple ipod family expands market apple has exp...
1489    santy worm makes unwelcome visit thousands of ...
Name: Text, Length: 1490, dtype: object

Importing neccessary modules

In [83]:
from nltk.tokenize import sent_tokenize, word_tokenize
import nltk
nltk.download('punkt')
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import nltk
nltk.download('stopwords')
import nltk
import string
nltk.download('wordnet')
import nltk
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.tokenize import word_tokenize
from collections import Counter

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


Preprocessing

In [84]:
def remove_stopwords(text):
	stop_words = set(stopwords.words("english"))
	word_tokens = word_tokenize(text)
	filtered_text = [word for word in word_tokens if word not in stop_words]
	return filtered_text

from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()


for i1 in range(len(df)):
    # print(len(df.loc[i1,'Text']))
    data = df.loc[i1,'Text']
    data = [data.lower()]

    # punc = '''!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~\n\t\\\€«§8»ş'''   
    # for ch in data:
    #   if ch in punc:
    #     data = data.replace(ch," ")
    translator = str.maketrans('', '', string.punctuation)
    data=[i.translate(translator) for i in data]

    data1=[]
    for i in data:
        data1.append(remove_stopwords(i))
        
    data2=[]

    for i in data1:
        s=""
        for j in i:
            s+=(j + ' ')
        data2.append(s)
            
    data = [" ".join(i.split()) for i in data2]
    # print(data[0])
    
    df.at[i1,'Text'] = data[0]
    
    print(len(df.loc[i1,'Text']))
    text = data[0]
    words = word_tokenize(text)

    # stemmer = PorterStemmer()

    stemmed_words = [lemmatizer.lemmatize(word) for word in words]

    # print("Stemmed words: ", stemmed_words)
    data3=[]

    s=""
    for j in stemmed_words:
        s+=(j + ' ')
        data3.append(s)
    
    df.at[i1,'Text'] = s
    

    
# print(df)

1424
1508
2145
2412
1583
1070
1320
937
2025
1033
2299
887
1038
1252
1710
1091
3107
1094
763
1103
1090
1281
672
1097
1416
1922
3426
4149
1182
1504
1826
1042
1521
860
1021
762
1309
862
1198
2033
1488
566
1088
2321
1814
1271
2987
1456
1357
914
1372
824
966
1082
1099
1575
1317
1101
1356
1274
2272
1820
1029
3326
720
552
1635
2073
1934
2425
1459
2567
813
1341
658
1007
801
724
1174
970
3076
1360
1517
1887
882
608
1680
1995
3516
1109
2965
1191
1901
1109
1718
1008
1067
965
1058
3060
1515
1126
840
1883
736
1642
4013
778
1192
1250
1277
1137
1172
1196
1446
1588
2620
616
1442
740
5965
1668
1075
2006
1542
2393
809
1531
1264
1764
1037
2632
1433
1609
2625
1058
1957
1461
538
1387
847
1334
1434
918
1460
1012
1500
783
959
2618
552
2262
2117
1953
2086
1253
1726
1029
2835
1070
1752
3099
987
441
1038
1222
1120
759
1355
854
1337
1158
1448
1135
849
1861
726
2082
1530
1434
1183
1249
1450
814
2249
2167
2212
2351
679
815
2946
2634
1808
1446
2130
1777
1719
883
554
878
1165
1087
2094
1461
2028
1347
685
557
3099
14

In [85]:
print(df.loc[0,'Text'])

worldcom exboss launch defence lawyer defending former worldcom chief bernie ebbers battery fraud charge called company whistleblower first witness cynthia cooper worldcom exhead internal accounting alerted director irregular accounting practice u telecom giant 2002 warning led collapse firm following discovery 11bn £57bn accounting fraud mr ebbers pleaded guilty charge fraud conspiracy prosecution lawyer argued mr ebbers orchestrated series accounting trick worldcom ordering employee hide expense inflate revenue meet wall street earnings estimate m cooper run consulting business told jury new york wednesday external auditor arthur andersen approved worldcom accounting early 2001 2002 said andersen given green light procedure practice used worldcom mr ebber lawyer said unaware fraud arguing auditor alert problem m cooper also said shareholder meeting mr ebbers often passed technical question company finance chief giving brief answer prosecution star witness former worldcom financial ch

In [123]:
df.drop('ArticleId', axis=1, inplace=True)


Current Dataframe

In [124]:
df

Text       Category
0     worldcom ex-boss launches defence lawyers defe...       business
1     german business confidence slides german busin...       business
2     bbc poll indicates economic gloom citizens in ...       business
3     lifestyle  governs mobile choice  faster  bett...           tech
4     enron bosses in $168m payout eighteen former e...       business
...                                                 ...            ...
1485  double eviction from big brother model caprice...  entertainment
1486  dj double act revamp chart show dj duo jk and ...  entertainment
1487  weak dollar hits reuters revenues at media gro...       business
1488  apple ipod family expands market apple has exp...           tech
1489  santy worm makes unwelcome visit thousands of ...           tech

[1490 rows x 2 columns]

In [88]:
words12=[]
for i in range(len(df)):
    words12.append(df['Text'][i])

Finding Unique words of whole dataset

In [89]:

tokenized_corpus = [x.split() for x in words12]

# print(tokenized_corpus)

# Create a set of unique words from the corpus
unique_words = set(word for doc in tokenized_corpus for word in doc)

Number of Unique words of dataset

In [90]:
print(len(unique_words))

24834


In [91]:
words = list(word for doc in tokenized_corpus for word in doc)

In [92]:
print(Counter(words))

Counter({'said': 4838, 'mr': 2006, 'year': 1853, 'would': 1711, 'also': 1426, 'new': 1334, 'people': 1323, 'u': 1227, 'one': 1190, 'could': 1032, 'game': 947, 'time': 939, 'first': 893, 'last': 883, 'say': 844, 'two': 816, 'world': 811, 'film': 802, 'government': 771, 'uk': 757, 'make': 695, 'company': 682, 'firm': 675, 'get': 626, 'number': 619, 'service': 617, 'best': 606, 'told': 591, 'made': 575, 'country': 564, 'many': 561, 'take': 557, 'month': 554, 'like': 550, '000': 545, 'market': 540, 'three': 535, 'week': 529, 'way': 526, 'player': 526, 'back': 521, 'music': 512, 'labour': 509, 'show': 509, 'next': 509, 'set': 508, 'election': 502, 'party': 498, 'sale': 497, 'win': 494, 'well': 483, 'bbc': 482, 'minister': 479, 'good': 478, 'plan': 478, 'may': 477, 'home': 477, 'want': 476, 'added': 465, 'work': 460, 'mobile': 457, 'day': 447, 'phone': 446, '2004': 441, 'go': 438, 'million': 436, 'right': 427, 'england': 427, 'group': 425, 'still': 421, 'play': 419, 'technology': 416, 'secon

Total categories of Dataset

In [93]:
df['Category'].unique()

array(['business', 'tech', 'politics', 'sport', 'entertainment'],
      dtype=object)

Generating 5 different corpus for 5 different categories

In [94]:
c1=[]
c2=[]
c3=[]
c4=[]
c5=[]
for i in range(len(df)):
    if(df['Category'][i]=='business'):
        c1.append(df['Text'][i])
    elif(df['Category'][i]=='tech'):
        c2.append(df['Text'][i])
    elif(df['Category'][i]=='politics'):
        c3.append(df['Text'][i])
    elif(df['Category'][i]=='sport'):
        c4.append(df['Text'][i])
    elif(df['Category'][i]=='entertainment'):
        c5.append(df['Text'][i])

In [95]:
tokenized_corpus = [x.split() for x in c1]

words1 = (word for doc in tokenized_corpus for word in doc)

tokenized_corpus2 = [x.split() for x in c2]

words2 = (word for doc in tokenized_corpus2 for word in doc)

tokenized_corpus3 = [x.split() for x in c3]

words3 = (word for doc in tokenized_corpus3 for word in doc)

tokenized_corpus4 = [x.split() for x in c4]

words4 = (word for doc in tokenized_corpus4 for word in doc)

tokenized_corpus5 = [x.split() for x in c5]

words5 = (word for doc in tokenized_corpus5 for word in doc)

Count number of times word appear in perticular category

In [96]:
from collections import Counter
w1=Counter(words1)
w2=Counter(words2)
w3=Counter(words3)
w4=Counter(words4)
w5=Counter(words5)

In [97]:
w1

Counter({'worldcom': 54,
         'exboss': 2,
         'launch': 23,
         'defence': 17,
         'lawyer': 26,
         'defending': 2,
         'former': 72,
         'chief': 154,
         'bernie': 8,
         'ebbers': 45,
         'battery': 1,
         'fraud': 64,
         'charge': 61,
         'called': 30,
         'company': 392,
         'whistleblower': 1,
         'first': 91,
         'witness': 10,
         'cynthia': 1,
         'cooper': 8,
         'exhead': 1,
         'internal': 8,
         'accounting': 35,
         'alerted': 1,
         'director': 71,
         'irregular': 2,
         'practice': 9,
         'u': 511,
         'telecom': 32,
         'giant': 68,
         '2002': 38,
         'warning': 14,
         'led': 32,
         'collapse': 24,
         'firm': 374,
         'following': 39,
         'discovery': 7,
         '11bn': 14,
         '£57bn': 3,
         'mr': 394,
         'pleaded': 12,
         'guilty': 25,
         'conspiracy': 5

Calculating TF-ICF values for all 5 corpus

In [98]:
import math
tficf={}
for i in w1:
    temp=[]
    # print(w1[i])
    tf1 = w1[i]
    cf = 1
    if i in w2:
        cf=cf+1
    if i in w3:
        cf=cf+1
    if i in w4:
        cf=cf+1
    if i in w5:
        cf=cf+1
    icf = math.log10(5/cf)
    tficf[i]=tf1*icf
    # temp.append(i)
    # temp.append(tf1*icf)
    # tficf.append(temp)

In [99]:
import math
tficf2={}
for i in w2:
    # print(w1[i])
    temp=[]
    tf = w1[i]
    cf = 1
    if i in w1:
        cf=cf+1
    if i in w3:
        cf=cf+1
    if i in w4:
        cf=cf+1
    if i in w5:
        cf=cf+1
    icf = math.log10(5/cf)
    tficf2[i]=tf1*icf
    # temp.append(i)
    # temp.append(tf*icf)
    # tficf2.append(temp)

In [100]:
import math
tficf3={}
for i in w3:
    # print(w1[i])
    temp=[]
    tf1 = w1[i]
    cf = 1
    if i in w2:
        cf=cf+1
    if i in w1:
        cf=cf+1
    if i in w4:
        cf=cf+1
    if i in w5:
        cf=cf+1
    icf = math.log10(5/cf)
    tficf3[i]=tf1*icf
    # temp.append(i)
    # temp.append(tf1*icf)
    # tficf3.append(temp)

In [101]:
import math
tficf4={}
for i in w4:
    # print(w1[i])
    temp=[]
    tf1 = w1[i]
    cf = 1
    if i in w2:
        cf=cf+1
    if i in w3:
        cf=cf+1
    if i in w1:
        cf=cf+1
    if i in w5:
        cf=cf+1
    icf = math.log10(5/cf)
    tficf4[i]=tf1*icf
    # temp.append(i)
    # temp.append(tf1*icf)
    # tficf4.append(temp)

In [102]:
import math
tficf5={}
for i in w5:
    # print(w1[i])
    temp=[]
    tf1 = w1[i]
    cf = 1
    if i in w2:
        cf=cf+1
    if i in w3:
        cf=cf+1
    if i in w4:
        cf=cf+1
    if i in w1:
        cf=cf+1
    icf = math.log10(5/cf)
    tficf5[i]=tf1*icf
    # temp.append(i)
    # temp.append(tf1*icf)
    # tficf5.append(temp)

In [103]:
print(len(tficf))
print(len(tficf2))
print(len(tficf3))
print(len(tficf4))
print(len(tficf5))

9559
9156
8466
8641
9339


Removing digits from unique words

In [104]:

uw = [x for x in unique_words if not any(c.isdigit() for c in x)]

In [105]:
len(uw)

22620

In [106]:
unique_words=set(uw)

In [107]:
len(unique_words)

22620

Generating list of list of TF-ICF values

In [108]:
gl=[]
for i in range(len(c1)):
    tl=['0']
    x = c1[i].split()
    for j in unique_words:
        flag=False
        for y in x:
            if ( j == y):
                tl.append(tficf[j])
                flag=True
                break
        if(flag==False):  
            tl.append(0.0)
    gl.append(tl)
    # break
    
for i in range(len(c2)):
    tl=['1']
    x = c2[i].split()
    for j in unique_words:
        flag=False
        for y in x:
            if ( j == y):
                tl.append(tficf2[j])
                flag=True
                break
        if(flag==False):  
            tl.append(0.0)
    gl.append(tl)
    
for i in range(len(c3)):
    tl=['2']
    x = c3[i].split()
    for j in unique_words:
        flag=False
        for y in x:
            if ( j == y):
                tl.append(tficf3[j])
                flag=True
                break
        if(flag==False):  
            tl.append(0.0)
    gl.append(tl)
    
for i in range(len(c4)):
    tl=['3']
    x = c4[i].split()
    for j in unique_words:
        flag=False
        for y in x:
            if ( j == y):
                tl.append(tficf4[j])
                flag=True
                break
        if(flag==False):  
            tl.append(0.0)
    gl.append(tl)
    
for i in range(len(c5)):
    tl=['4']
    x = c5[i].split()
    for j in unique_words:
        flag=False
        for y in x:
            if ( j == y):
                tl.append(tficf5[j])
                flag=True
                break
        if(flag==False):  
            tl.append(0.0)
    gl.append(tl)

Buildig Dataframe( 2D Matrix ) of above list of list

In [128]:
fd= pd.DataFrame(gl)

In [129]:
fd

0      1      2      3      4      5      6      7      8      9      \
0        0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1        0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2        0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3        0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
4        0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
...    ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
1485     4    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1486     4    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1487     4    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1488     4    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1489     4    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

      ...  22611  22612  22613  22614  22615  22616  22617  22618  22619  \
0     ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1     ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2     ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3     ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
4     ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
...   ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
1485  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1486  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1487  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1488  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1489  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

      22620  
0       0.0  
1       0.0  
2       0.0  
3       0.0  
4       0.0  
...     ...  
1485    0.0  
1486    0.0  
1487    0.0  
1488    0.0  
1489    0.0  

[1490 rows x 22621 columns]

In [130]:
import numpy as np
fd = fd.replace(np.nan,0.0)
fd

0      1      2      3      4      5      6      7      8      9      \
0        0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1        0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2        0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3        0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
4        0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
...    ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
1485     4    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1486     4    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1487     4    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1488     4    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1489     4    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

      ...  22611  22612  22613  22614  22615  22616  22617  22618  22619  \
0     ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1     ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2     ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3     ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
4     ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
...   ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
1485  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1486  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1487  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1488  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1489  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

      22620  
0       0.0  
1       0.0  
2       0.0  
3       0.0  
4       0.0  
...     ...  
1485    0.0  
1486    0.0  
1487    0.0  
1488    0.0  
1489    0.0  

[1490 rows x 22621 columns]

In [131]:
from sklearn import preprocessing

le = preprocessing.LabelEncoder()
fd[0]= le.fit_transform(fd[0])

vector_matrix_df = fd.sample(frac = 1).reset_index(drop=True)
vector_matrix_df

0      1      2      3      4      5      6      7      8      9      \
0         3    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1         0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2         3    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3         3    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
4         0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
...     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
1485      0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1486      2    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1487      0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1488      3    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1489      2    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

      ...  22611  22612  22613  22614  22615  22616  22617  22618  22619  \
0     ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1     ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2     ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3     ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
4     ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
...   ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
1485  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1486  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1487  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1488  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1489  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

      22620  
0       0.0  
1       0.0  
2       0.0  
3       0.0  
4       0.0  
...     ...  
1485    0.0  
1486    0.0  
1487    0.0  
1488    0.0  
1489    0.0  

[1490 rows x 22621 columns]

Conditional Probability calculation for naive base classifier

In [ ]:
prob_c1= len(c1)/len(vector_matrix_df)
prob_c2= len(c2)/len(vector_matrix_df)
prob_c3= len(c3)/len(vector_matrix_df)
prob_c4= len(c4)/len(vector_matrix_df)
prob_c5= len(c5)/len(vector_matrix_df)

In [ ]:
print(prob_c1)
print(prob_c2)
print(prob_c3)
print(prob_c4)
print(prob_c5)

In [ ]:
total_sum=0
for i in w1:
  total_sum=total_sum+tficf[i]

total_sum2=0
for i in w2:
  total_sum2=total_sum2+tficf2[i]

total_sum3=0
for i in w3:
  total_sum3=total_sum3+tficf3[i]

total_sum4=0
for i in w4:
  total_sum4=total_sum4+tficf4[i]

total_sum5=0
for i in w5:
  total_sum5=total_sum5+tficf5[i]

Probabilty of each word for given category 

In [ ]:
prob_feature_c1=[]

for i in w1:
    temp=[]
    temp1=tficf[i]/total_sum
    temp.append(i)
    temp.append(temp1)
    prob_feature_c1.append(temp)
    
prob_feature_c2=[]

for i in w2:
    temp=[]
    temp1=tficf2[i]/total_sum
    temp.append(i)
    temp.append(temp1)
    prob_feature_c2.append(temp)
    
prob_feature_c3=[]

for i in w3:
    temp=[]
    temp1=tficf3[i]/total_sum
    temp.append(i)
    temp.append(temp1)
    prob_feature_c3.append(temp)
    
prob_feature_c4=[]

for i in w4:
    temp=[]
    temp1=tficf4[i]/total_sum
    temp.append(i)
    temp.append(temp1)
    prob_feature_c4.append(temp)
    
prob_feature_c5=[]

for i in w5:
    temp=[]
    temp1=tficf5[i]/total_sum
    temp.append(i)
    temp.append(temp1)
    prob_feature_c5.append(temp)
    


split, Train and Test Model using Naive base classifier 

70-30 Split

In [132]:
from sklearn.model_selection import train_test_split
from sklearn import metrics


X_train, X_test, y_train, y_test = train_test_split(vector_matrix_df.drop(0, axis=1), vector_matrix_df[0],
                                   test_size=0.3, 
                                   shuffle=True)

from sklearn.naive_bayes import MultinomialNB

naive_bayes_classifier = MultinomialNB()
naive_bayes_classifier.fit(X_train, y_train)


y_pred = naive_bayes_classifier.predict(X_test)

score = metrics.accuracy_score(y_test, y_pred)

print(metrics.confusion_matrix(y_test, y_pred))

print(pd.DataFrame(metrics.classification_report(y_test, y_pred, output_dict=True)))


print(score)

[[105   0   1   0   0]
 [  0  70   0   0   0]
 [ 14   0  71   0   2]
 [  6   0   2  92   0]
 [ 19   0   7   4  54]]
                    0     1          2           3          4  accuracy  \
precision    0.729167   1.0   0.876543    0.958333   0.964286  0.876957   
recall       0.990566   1.0   0.816092    0.920000   0.642857  0.876957   
f1-score     0.840000   1.0   0.845238    0.938776   0.771429  0.876957   
support    106.000000  70.0  87.000000  100.000000  84.000000  0.876957   

            macro avg  weighted avg  
precision    0.905666      0.895714  
recall       0.873903      0.876957  
f1-score     0.879088      0.875287  
support    447.000000    447.000000  
0.8769574944071589


50-50 split

In [133]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(vector_matrix_df.drop(0, axis=1), vector_matrix_df[0],
                                   random_state=104, 
                                   test_size=0.5, 
                                   shuffle=True)

from sklearn.naive_bayes import MultinomialNB

naive_bayes_classifier = MultinomialNB()
naive_bayes_classifier.fit(X_train, y_train)

from sklearn import metrics

y_pred = naive_bayes_classifier.predict(X_test)

score = metrics.accuracy_score(y_test, y_pred)

print(metrics.confusion_matrix(y_test, y_pred))

print(pd.DataFrame(metrics.classification_report(y_test, y_pred, output_dict=True)))

print(score)

[[177   0   2   0   0]
 [  0 123   0   0   0]
 [ 27   0 113   1   0]
 [  2   0   1 161   0]
 [ 33   0  11   5  89]]
                    0      1           2           3           4  accuracy  \
precision    0.740586    1.0    0.889764    0.964072    1.000000  0.889933   
recall       0.988827    1.0    0.801418    0.981707    0.644928  0.889933   
f1-score     0.846890    1.0    0.843284    0.972810    0.784141  0.889933   
support    179.000000  123.0  141.000000  164.000000  138.000000  0.889933   

            macro avg  weighted avg  
precision    0.918884      0.908898  
recall       0.883376      0.889933  
f1-score     0.889425      0.887582  
support    745.000000    745.000000  
0.8899328859060402


80-20 split

In [136]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(vector_matrix_df.drop(0, axis=1), vector_matrix_df[0],
                                   random_state=104, 
                                   test_size=0.2, 
                                   shuffle=True)

from sklearn.naive_bayes import MultinomialNB

naive_bayes_classifier = MultinomialNB()
naive_bayes_classifier.fit(X_train, y_train)

from sklearn import metrics

y_pred = naive_bayes_classifier.predict(X_test)

score = metrics.accuracy_score(y_test, y_pred)

print(metrics.confusion_matrix(y_test, y_pred))

print(pd.DataFrame(metrics.classification_report(y_test, y_pred, output_dict=True)))
print(score)

[[70  0  1  0  0]
 [ 0 56  0  0  0]
 [ 5  0 45  0  0]
 [ 0  0  0 67  0]
 [10  0  2  0 42]]
                   0     1          2     3          4  accuracy   macro avg  \
precision   0.823529   1.0   0.937500   1.0   1.000000  0.939597    0.952206   
recall      0.985915   1.0   0.900000   1.0   0.777778  0.939597    0.932739   
f1-score    0.897436   1.0   0.918367   1.0   0.875000  0.939597    0.938161   
support    71.000000  56.0  50.000000  67.0  54.000000  0.939597  298.000000   

           weighted avg  
precision      0.947468  
recall         0.939597  
f1-score       0.939216  
support      298.000000  
0.9395973154362416


60-40 split

In [137]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(vector_matrix_df.drop(0, axis=1), vector_matrix_df[0],
                                   random_state=104, 
                                   test_size=0.4, 
                                   shuffle=True)

from sklearn.naive_bayes import MultinomialNB

naive_bayes_classifier = MultinomialNB()
naive_bayes_classifier.fit(X_train, y_train)

from sklearn import metrics

y_pred = naive_bayes_classifier.predict(X_test)

score = metrics.accuracy_score(y_test, y_pred)

print(metrics.confusion_matrix(y_test, y_pred))

print(pd.DataFrame(metrics.classification_report(y_test, y_pred, output_dict=True)))

print(score)

[[151   0   3   0   0]
 [  0  93   0   0   0]
 [ 12   0  99   0   1]
 [  3   0   0 128   0]
 [ 26   0   4   0  76]]
                    0     1           2           3           4  accuracy  \
precision    0.786458   1.0    0.933962    1.000000    0.987013  0.917785   
recall       0.980519   1.0    0.883929    0.977099    0.716981  0.917785   
f1-score     0.872832   1.0    0.908257    0.988417    0.830601  0.917785   
support    154.000000  93.0  112.000000  131.000000  106.000000  0.917785   

            macro avg  weighted avg  
precision    0.941487      0.930104  
recall       0.911706      0.917785  
f1-score     0.920021      0.917227  
support    596.000000    596.000000  
0.9177852348993288


TF-IDF based model traing and testing

In [138]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import make_pipeline
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


data = df['Text']

label = df['Category']

# sample training data
X_train, X_test, y_train, y_test = train_test_split(data, label, test_size=0.3, random_state=42)

# initialize the classifier with TF-IDF weighting scheme
classifier = make_pipeline(TfidfVectorizer(), MultinomialNB())

# fit the model with the training data
classifier.fit(X_train, y_train)

# predict the labels of the test data
predicted_labels = classifier.predict(X_test)

# calculate the accuracy
accuracy = accuracy_score(y_test,predicted_labels)

# print the accuracy
print(f"Accuracy: {accuracy}")



Accuracy: 0.9574944071588367


Testing on Test data given in assignment

In [153]:
df_test = pd.read_csv('/content/BBC News Test.csv')

df_test

ArticleId                                               Text
0         1018  qpr keeper day heads for preston queens park r...
1         1319  software watching while you work software that...
2         1138  d arcy injury adds to ireland woe gordon d arc...
3          459  india s reliance family feud heats up the ongo...
4         1020  boro suffer morrison injury blow middlesbrough...
..         ...                                                ...
730       1923  eu to probe alitalia  state aid  the european ...
731        373  u2 to play at grammy awards show irish rock ba...
732       1704  sport betting rules in spotlight a group of mp...
733        206  alfa romeos  to get gm engines  fiat is to sto...
734        471  citizenship event for 18s touted citizenship c...

[735 rows x 2 columns]

Final predicted categories for test data

In [158]:
X_test = df_test['Text']

predicted_labels = classifier.predict(X_test)

print(predicted_labels)


['sport' 'tech' 'sport' 'business' 'sport' 'sport' 'politics' 'politics'
 'entertainment' 'business' 'business' 'tech' 'politics' 'tech'
 'entertainment' 'sport' 'politics' 'tech' 'entertainment' 'sport'
 'business' 'politics' 'sport' 'business' 'politics' 'sport' 'business'
 'sport' 'sport' 'business' 'politics' 'tech' 'business' 'business'
 'sport' 'sport' 'sport' 'business' 'entertainment' 'business' 'tech'
 'politics' 'entertainment' 'tech' 'sport' 'tech' 'entertainment'
 'business' 'politics' 'business' 'politics' 'business' 'business'
 'business' 'tech' 'politics' 'tech' 'sport' 'sport' 'tech' 'sport'
 'entertainment' 'tech' 'politics' 'business' 'entertainment' 'sport'
 'tech' 'sport' 'sport' 'tech' 'sport' 'business' 'politics' 'tech'
 'sport' 'tech' 'tech' 'tech' 'entertainment' 'politics' 'sport'
 'entertainment' 'sport' 'business' 'entertainment' 'business'
 'entertainment' 'business' 'tech' 'business' 'politics' 'sport' 'tech'
 'sport' 'sport' 'sport' 'sport' 'sport' 'sport